version: '3'

services:
  web:
    image: python:3.9-slim
    container_name: qq_reader
    working_dir: /app/qq_reader
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    command: >
      bash -c "pip install -r requirements.txt && python app.py"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped